-- 0020_reflow_pyq_stems.sql
--
-- Put the line breaks back into past-paper question stems.
--
-- The loader in 0014/0015 joined every line of a stem with a single space, so
-- an RPSC match-the-list question arrived as one unbroken paragraph:
--
--   Match List I with List II ... select the correct option: List - I A.
--   Kishangarh B. Bikaner C. Mewar D. Marwar List - II i. Sahibdeen ii.
--   Nihalchand iii. Ali Raza iv. Shivdas Codes:
--
-- which is close to unreadable under time pressure, and is not how the paper
-- set it. The source .docx had one paragraph per line all along; the join threw
-- that structure away.
--
-- Stems are now stored with newlines and matched on (source_year, paper_qno),
-- the numbering added by 0016. The screens already render with
-- `whitespace-pre-line`, so nothing in the app needs to change.

update public.questions t set q = v.stem
from (values
  ('2018',1,E'Which of the following statements is/are true?\n(A) After the Nagpur Session (1920) of Congress, the provincial Congress Committees were constituted on a linguistic basis.\n(B) In 1948, Congress rejected the demand for the formation of provinces on a linguistic basis.\nSelect the correct answer from the code below:'),
  ('2018',2,E'Sixteen coins of King Menander have been found from which of the following sites?'),
  ('2018',3,E'Which of the following rulers does not belong to the Gurjara-Pratihar dynasty?'),
  ('2018',4,E'In pre-medieval kingdoms of Rajasthan, what was the designation "Naimittika" used for?'),
  ('2018',5,E'Which revolutionary was convicted in the Mahant Pyarelal Murder case?'),
  ('2018',6,E'Who among the following negotiated the Subordinate Alliances of 1817-18 with the Princely States of Rajputana?'),
  ('2018',7,E'Which princely state was not part of the Rajasthan Union formed on March 25, 1948?'),
  ('2018',8,E'Who was the editor of ''Tyag Bhumi''?'),
  ('2018',9,E'Match the following temples with their districts:\nTemple\ni. Kameshwar Mahadev\nii. Shitaleshwar\niii. Pipala Mata\niv. Nilkantha\nDistrict\na. Alwar\nb. Jodhpur\nc. Jhalawar\nd. Pali\nChoose the correct codes:'),
  ('2018',10,E'Which of the following temples in Chittorgarh Fort is a Jain temple?'),
  ('2018',11,E'Which of the following painters does not belong to the Alwar School of Painting?'),
  ('2018',12,E'Which of the following pairs of work and author is not correctly matched?'),
  ('2018',13,E'What singing tradition was Gavari Devi associated with?'),
  ('2018',14,E'The female saint Daya Bai was a disciple of whom?'),
  ('2018',15,E'Which dance form is related to the Garasia Tribe?'),
  ('2018',16,E'Consider the following statements about Vijaydan Detha:\n(A) Vijaydan Detha was a famous writer from Rajasthan whose story was adapted into the play Charandas Chor.\n(B) Vijaydan Detha was a co-founder of the Rupayan Sansthan.\nChoose the correct answer:'),
  ('2018',17,E'Match the mountain peaks with their locations:\nMountain Peak\nA. Elbrus\nB. Kilimanjaro\nC. Mt. Cook\nD. McKinley\nLocation/Country\n(i) New Zealand\n(ii) U.S.A.\n(iii) Tanzania\n(iv) Russia\nCodes:'),
  ('2018',18,E'Among the mathematical indices for measuring biodiversity, which one shows the mean species diversity in a habitat at a local scale?'),
  ('2018',19,E'Which industrial region and country pair is not a correct match?'),
  ('2018',20,E'Match the canals with the water bodies they connect:\nCanal\nA. Kiel\nB. Soo\nC. Panama\nD. Suez\nConnects\n(i) Mediterranean Sea & Red Sea\n(ii) Elbe estuary & Baltic Sea\n(iii) Atlantic Ocean & Pacific Ocean\n(iv) Lake Superior & Lake Huron\nCodes:'),
  ('2018',21,E'Which of the following mountain peaks is not situated in the Eastern Ghats?'),
  ('2018',22,E'Which pair of shifting agriculture and state is not a correct match?'),
  ('2018',23,E'Match the protected areas of India with their numbers as of 2018:\nProtected areas of India\nA. Community Reserves\nB. Conservation Reserves\nC. National Parks\nD. Wildlife Sanctuaries\nNumber in 2018\n(i) 103\n(ii) 46\n(iii) 544\n(iv) 76\nCodes:'),
  ('2018',24,E'Bharat Electronics Ltd. (BEL) is collaborating with ISRO to develop what?'),
  ('2018',25,E'Match the mountains with their respective districts:\nDistrict\nA. Jalore\nB. Jaipur\nC. Alwar\nD. Sikar\nMountain\n(i) Barwada\n(ii) Jharola\n(iii) Raghunathgarh\n(iv) Bhangarh\nCodes:'),
  ('2018',26,E'Which of the given hills in Rajasthan is an extension of the Vindhyan ranges?'),
  ('2018',27,E'Match the major irrigation projects with their beneficiary districts:\nMajor irrigation project\nA. Sidhmukh Project\nB. Narmada Project\nC. Jawai Project\nD. Jakham Project\nBeneficiary districts\n(i) Jalore and Barmer\n(ii) Jalore, Pali, and Jodhpur\n(iii) Udaipur and Pratapgarh\n(iv) Hanumangarh and Churu\nCodes:'),
  ('2018',28,E'What causes the dust storms that originate in Rajasthan during May and June?\n(A) Origin of convectional currents at a few places\n(B) The Aravalli hills are parallel to the south-western winds\n(C) Origin of fast, speedy easterly winds'),
  ('2018',29,E'Which of the following statements are correct?\n(A) Marble Development and Conservation Rule - 2002\n(B) Rajasthan Mineral Policy - 2015\n(C) District Mineral Foundation Trust Rules - 2016\n(D) Rajasthan Minor Mineral Concession Rules (Amended up to May 2016)\nCodes:'),
  ('2018',30,E'Rajasthan is almost the sole producer of which of the following minerals?\n(A) Lead and zinc ores\n(B) Copper ores\n(C) Wollastonite\n(D) Selenite\nCodes:'),
  ('2018',31,E'From which area of Rajasthan was the maximum crude oil produced in the year 2017-18 (up to Dec. 2017)?'),
  ('2018',32,E'According to the 2011 census, what is the percentage of the urban population in India and Rajasthan, respectively?'),
  ('2018',33,E'Which of the following are important mineral-based industries in Rajasthan?\n(A) Zinc smelting industry\n(B) Cement industry\n(C) Electronic industry\n(D) Marble industry\nCodes:'),
  ('2018',34,E'As per the 2011 census, which districts of Rajasthan have the lowest percentage of Scheduled Tribe population in their total population?'),
  ('2018',35,E'The proposed oil refinery at Pachpadra, Barmer is a joint venture of which entities?'),
  ('2018',36,E'Which district and mascot pair is not a correct match?'),
  ('2018',37,E'Which of the following elections for the Central Legislative Assembly were held under the Government of India Act, 1919?\n(A) 1926\n(B) 1937\n(C) 1945\nSelect the correct answer using the code given below:'),
  ('2018',38,E'Who authored Gandhian Constitution for Free India?'),
  ('2018',39,E'Which of the following statements regarding the Indian Constituent Assembly are correct?\n(A) It was not based on Adult franchise.\n(B) It resulted from direct elections.\n(C) It was not a multi-party body.\n(D) It worked through several committees.\nSelect the correct answer using the code given below:'),
  ('2018',40,E'The provision, "The age of a Judge of the Supreme Court of India shall be determined by such authority and in such manner as Parliament may by law provide," was inserted by which amendment?'),
  ('2018',41,E'Select the correct chronological order of the following judgments dealing with Fundamental Rights:\n(A) Golaknath v/s State of Punjab\n(B) Keshavananda Bharati v/s State of Kerala\n(C) Minerva Mills v/s Union of India\n(D) A. K. Gopalan v/s State of Madras\nSelect the correct answer:'),
  ('2018',42,E'Which of the following were members of the Swaran Singh Committee (1976)?\n(A) A. R. Antulay\n(B) S. S. Ray\n(C) Haridev Joshi\n(D) C. M. Stephen\nSelect the correct answer using the code given below:'),
  ('2018',43,E'Which one of the following pairs is not correctly matched regarding the President''s power to make regulations for certain Union Territories under Article 240 of the Indian Constitution?'),
  ('2018',44,E'On which date did the President of India, using his powers, declare that a grave emergency existed where the security of India was threatened by internal disturbance?'),
  ('2018',45,E'Under Article 87 of the Indian Constitution, the President of India addresses:'),
  ('2018',46,E'Under Rule 377 of the Rules of Procedure and Conduct of Business in Lok Sabha, what is the maximum number of matters that can be raised by members in one day?'),
  ('2018',47,E'Which of the following are the Financial Committees of the Indian Parliament?\n(A) Estimates Committee\n(B) Public Accounts Committee\n(C) Committee on Public Undertakings\n(D) Joint Committee on Salaries and Allowances for Members of Parliament\nSelect the correct answer using the code given below:'),
  ('2018',48,E'The Comptroller and Auditor-General of India can be removed from office in a manner similar to whom?'),
  ('2018',49,E'The Central Vigilance Commission was set up on the recommendation of:'),
  ('2018',50,E'In which country did the concept of Public Interest Litigation (PIL) originate?'),
  ('2018',51,E'Which of the following terms is/are mentioned in the Preamble of the Right to Information Act, 2005?1\n(A) Transparency of Information2\n(B) Revelation of Information3\n(C) Informed Citizenry4\n(D) Paramountcy of the democratic ideal5\nSelect the correct an6swer using the code given below:'),
  ('2018',52,E'Match the authors with their books:\nAuthors\n(A) Atul Kohli\n(B) Granville Austin\n(C) Penderel Moon\n(D) Alan Gledhill\nBooks\n(i) Divide and Quit\n(ii) The Success of India''s Democracy\n(iii) The Republic of India: Development of its Laws and Constitution\n(iv) Working a Democratic Constitution: A History of the Indian Experience\nCodes:'),
  ('2018',53,E'Under the provisions of Article 368(2) of the Constitution of India, if a bill, after being passed by the Parliament of India, comes to the Rajasthan Legislative Assembly for ratification, then:\n(A) The Assembly can pass the resolution.\n(B) The Assembly can reject the resolution.\n(C) No amendment shall be proposed to such a resolution.\nSelect the correct answer using the code given below:'),
  ('2018',54,E'Which of the following Acts/Rules of Rajasthan has a provision for a joint meeting of the Gram Sabha?'),
  ('2018',55,E'Which of the following Chief Ministers have not held the post of the Leader of the Opposition in the Rajasthan Legislative Assembly?\n(A) Haridev Joshi\n(B) Shivcharan Mathur\n(C) Ashok Gehlot\n(D) Vasundhara Raje\nSelect the correct answer using the code given below:'),
  ('2018',56,E'After receiving a complaint against the following office bearers, against whom can the Lokayukta of Rajasthan not conduct an investigation?'),
  ('2018',57,E'Which of the following statements are correct in the context of the Rajasthan State Human Rights Commission?\n(A) It was constituted on January 18, 1999, by a notification from the Government of Rajasthan.\n(B) The Commission became functional in March 2000.\n(C) The Rajasthan Human Rights Commission has one chairperson and 3 members in accordance with the provision of the Protection of Human Rights (Amendment) Act, 2006.\n(D) One of its former Chairmen was a retired judge of the Supreme Court of India.\nSelect the correct answer using the code given below:'),
  ('2018',58,E'Which one of the following judges of the Supreme Court of India has not worked as a judge in the Rajasthan High Court?'),
  ('2018',59,E'Who among the following has held the posts of Protem Speaker, Speaker, and Deputy Speaker of the Rajasthan Legislative Assembly?'),
  ('2018',60,E'Which of the following statements are correct in reference to the rule of procedure for a ''Motion for Adjournment on a matter of Public importance'' in the Rajasthan Legislative Assembly?\n(A) The Speaker''s consent is necessary to make the motion.\n(B) The motion shall raise a question of privilege.\n(C) The motion shall be restricted to a specific matter of recent occurrence.\n(D) Not more than one such motion shall be made at the same sitting.\nSelect the correct answer using the code given below:'),
  ('2018',61,E'A bill required the recommendation of the Governor under a constitutional provision, but it was introduced in the Rajasthan Legislative Assembly without it, passed, and sent to the Governor. Now:'),
  ('2018',62,E'What has been kept under the purview of the Goods and Services Tax (GST)?'),
  ('2018',63,E'Which of the following fixed the four percent inflation target in India with a tolerance level of +/-2 percent for the period 2016 to 2021?'),
  ('2018',64,E'In terms of the share in Foreign Direct Investment Equity inflows in India during 2016-17, which of the following countries was on top?'),
  ('2018',65,E'Why do companies go for business process re-engineering with the help of technology?'),
  ('2018',66,E'The most volatile part of the Organised Money Market in India is:'),
  ('2018',67,E'Which one of the following is not included in the revenue account of the Union Budget?'),
  ('2018',68,E'The Eleventh Five-Year Plan emphasised:'),
  ('2018',69,E'Assertion (A): Cost-push inflation is caused by a shift in the aggregate supply curve.\nReason (R): A shift in the aggregate supply curve takes place because of an increase in wages.'),
  ('2018',70,E'What is the base year of Rajasthan''s general Wholesale Price Index?'),
  ('2018',71,E'What was the growth rate of GSDP (Gross State Domestic Product) at constant prices (2011-12) for the year 2017-18 in Rajasthan?'),
  ('2018',72,E'Which of the following items has provided the maximum revenue in the Revenue Receipts of the Rajasthan budget in recent years?'),
  ('2018',73,E'Which of the following thermal power projects has the highest installed power capacity?'),
  ('2018',74,E'The Rajasthan Government has established the first Skill University in the state. Where was it established?'),
  ('2018',75,E'Which of the following is not a Unique Selling Proposition (USP) of Rajasthan in the tourism sector?'),
  ('2018',76,E'Which of the following is not considered an oil field in Rajasthan?'),
  ('2018',77,E'Which one of the following lakes of Rajasthan is not covered under the National Lake Conservation Programme (NLCP)?'),
  ('2018',78,E'The Government of Rajasthan''s Post-Matric Scholarship Scheme for students of minority communities provides financial assistance to those having a specific combination of parental income and percentage of marks in the previous examination. What is that combination?'),
  ('2018',79,E'What is the main objective of the Swavalamban Yojana in Rajasthan?'),
  ('2018',80,E'The Mitigating Poverty in Western Rajasthan (MPoWR) Programme is supported by:'),
  ('2018',81,E'In which of the following projects has the sprinkler irrigation system been made compulsory for the first time in Rajasthan?'),
  ('2018',82,E'Which of the following is an example of a non-cellulosic fibre?'),
  ('2018',83,E'The waves used in a common TV remote control are:'),
  ('2018',84,E'Which metal is generally used for coating brass utensils to prevent copper contamination?'),
  ('2018',85,E'Waves of the Ultra High Frequency (UHF) range normally propagate by means of:'),
  ('2018',86,E'The machine language of a computer is based on:'),
  ('2018',87,E'Which of the following statements correctly describes a difference between Bluetooth and Wi-Fi?'),
  ('2018',88,E'Consider the following pairs of ISRO Centres and their locations:\nA. Vikram Sarabhai Space Centre (VSSC) - Trivandrum (Kerala)7\nB. UR Rao Satellite Centre (URSC) - Bengaluru (Karnataka)8\nC. National Remote Sensing Centre (NRSC) - Dehradun (Uttarakhand)9\nD. Indian Institute of Remote Sensing (IIRS) - Hyderabad (Telangana)10\nWhich of the above pairs are correctly matched11?'),
  ('2018',89,E'Which of the following polyherbal products has NOT been developed by the Defence Research and Development Organisation (DRDO)?'),
  ('2018',90,E'What is India''s first Beyond-Visual-Range (BVR) air-to-air missile, indigenously designed & developed by the DRDO?'),
  ('2018',91,E'How many satellites were launched successfully by PSLV-C37 in a single flight on February 15, 2017?'),
  ('2018',92,E'A particle having at least one dimension less than 10-7 metre is known as a:'),
  ('2018',93,E'Match Column I with Column II:\nColumn I\nA. Grape Sugar\nB. Fruit Sugar\nC. Milk Sugar\nD. Table Sugar\nE. Stevia\nColumn II\n(i) Fructose\n(ii) Sucrose\n(iii) Natural Sweetener\n(iv) Glucose\n(v) Lactose\nCodes:'),
  ('2018',94,E'In humans, the trisomy of chromosome number 21 is responsible for:'),
  ('2018',95,E'The total amount of greenhouse gases produced to directly and indirectly support human activities is referred to as:'),
  ('2018',96,E'Which of the following environmental pollutants are responsible for "acid rain"?'),
  ('2018',97,E'Which of the following plants, grown in non-forest areas, has been omitted from the definition of "trees" in the Indian Forest (Amendment) Act 2017?'),
  ('2018',98,E'The basis of DNA fingerprinting is:'),
  ('2018',99,E'The National Research Centre on Seed Spices is located at:'),
  ('2018',100,E'Which of the following statements is incorrect in reference to compost?'),
  ('2018',101,E'The solar observatory in Rajasthan is located at:'),
  ('2018',102,E'In this question, a statement is followed by two assumptions.\nStatement: Though he is fat, yet he runs fast.\nAssumptions:\nI: Fat people have weak muscles.\nII: Fat people generally cannot run fast.\nWhich of the answers is correct?'),
  ('2018',103,E'Consider the following:\nStatement: Should there be recruitment in Government service on the basis of past academic performance rather than through competitive examinations?\nArguments:\nI. Yes, it will be beneficial for those candidates who are unable to bear the expenses of competitive examinations.\nII. No, past academic performance cannot be made the basis of recruitment because there is no uniformity in the assessment by the Universities.\nWhich one is/are the strong argument(s)?'),
  ('2018',104,E'Statements: All branches are flowers. All flowers are leaves.\nConclusions:\nI. All branches are leaves.\nII. Some leaves are branches.\nIII. All flowers are branches.\nIV. All leaves are branches.\nGive Answers:'),
  ('2018',105,E'A statement with two courses of action is given below. Assume everything in the statement to be true and decide which of the suggested courses of action logically follows.\nStatement: A large number of employees have gone on a mass casual leave in protest against the company''s new recruitment policy.\nCourses of action:\nI. The company should immediately withdraw the new recruitment policy.\nII. All these employees should immediately be suspended from their service.\nGiven answer:'),
  ('2018',107,E'If 4+5-2=33 and 10+12-5=119, then 6+8-3=?'),
  ('2018',109,E'Pick out the odd one:'),
  ('2018',110,E'In a code language:\nI: "lew nas hsi ploy" means "she is bringing coffee".\nII: "wir sut lew ploy" means "he is bringing tea".\nIII: "sut lim nas" means "tea and coffee".\nWhich word has been used for "he"?'),
  ('2018',111,E'Mr. A meets Mr. B. B is the father of a son C and a daughter D. E is the mother of A. C is married and has one son. E is the daughter-in-law of B. How is A related to B?'),
  ('2018',112,E'If x, y, z are natural numbers, then the number of different solutions of the equation x+y+z=6 are:'),
  ('2018',113,E'The product of three consecutive positive numbers is divided by each of them in turn. The sum of the three quotients is 74. What is the sum of the three numbers?'),
  ('2018',114,E'Two alloys are made from gold and copper in the ratios of 7:2 and 7:11, respectively. Equal quantities of both alloys are mixed to make a third alloy. In this third alloy, what is the ratio of gold to copper?'),
  ('2018',115,E'On a construction site, men, women, and children are working in the ratio of 9:4:1. Their wages are in the ratio of 8:5:3. If 60 women are working on this site and the total daily wages of all persons is Rs. 2,850, what are the daily wages of a child?'),
  ('2018',116,E'The population of a small city is 9,26,100. If it increases at the rate of 5% per annum, what was the population 2 years ago?'),
  ('2018',117,E'The difference between the compound interest and simple interest on a certain sum at 10% per annum for 2 years is Rs. 874. Find the sum.'),
  ('2018',118,E'A sum of money at a certain rate of compound interest doubles in 3 years. In 9 years, it will be k times the original principal. What is the value of k?'),
  ('2018',119,E'Which vehicle type showed the minimum percentage increase from 2000-01 to 2010-11?'),
  ('2018',120,E'If the percentage increase in the total number of vehicles from 2000-01 to 2010-11 were equal to the percentage increase from 1990-91 to 2000-01, what would the total number of vehicles (in lakhs) in 2010-11 be?'),
  ('2018',121,E'By what percentage does the total expenditure on transport and food in July exceed that of June? (approximately)'),
  ('2018',122,E'A new software has been launched by the Rajasthan government for monitoring seasonal and non-communicable diseases, as well as the trends of ailments found in specific areas. What is the name of this software?'),
  ('2018',124,E'An Indian-American woman has been named the Chief Financial Officer of General Motors, the largest automaker in the United States. What is her name?'),
  ('2018',125,E'Why was Sharad Kumar, former Director-General of the National Investigation Agency, in the news recently?'),
  ('2018',126,E'Bangladesh won the Women''s Cricket Asia Cup Trophy (Twenty-20 Tournament) held in Malaysia in June 2018. Which team was defeated in the finals?'),
  ('2018',127,E'Consider the following statements regarding the first Mega Food Park of Rajasthan, established in March 2018:\n(A) It was inaugurated by Union Minister for Food Processing Industries Harsimrat Kaur Badal.\n(B) It is known as the Smart Mega Food Park.\n(C) It is located at Roopangarh in Ajmer.\nWhich of the statements given above is/are correct?'),
  ('2018',128,E'Where was the historic meeting between U.S. President Donald Trump and North Korea''s leader Kim Jong Un held in June 2018?'),
  ('2018',130,E'The Haryana Government has launched a 7-Star Gram Panchayat Rainbow Scheme to give star rankings to its panchayats based on seven social parameters. What star ranking is given to panchayats that show outstanding performance in improving the sex ratio?'),
  ('2018',132,E'Recently, the capital of one of the North-Eastern States was declared the 100th Smart City by the Ministry of Housing and Urban Affairs. Which state is it?'),
  ('2018',134,E'What solar power capacity target has the Government of India set to achieve by the year 2022?'),
  ('2018',135,E'Recently, India''s Deepika Kumari won the gold medal in the Women''s Recurve event at the Archery World Cup (Stage III). Where was this competition held?'),
  ('2018',136,E'After the appointment of Justice Indu Malhotra, the number of female judges in the Supreme Court of India has reached two. Who is the other female judge?'),
  ('2018',138,E'Consider the following statements about the Electoral Bond Scheme 2018:\n(A) The aim of this scheme is to bring transparency to the funding process of political parties.\n(B) Only political parties recognized by the Election Commission that secured not less than two percent of the votes polled in the last general election are eligible to receive Electoral Bonds.\n(C) Electoral Bonds shall be valid for fifteen calendar days from the date of issue.\n(D) An Electoral Bond deposited by an eligible political party into its account shall be credited on the same day.\nWhich of the above statements are correct?'),
  ('2018',139,E'Recently, which space agency successfully launched the world''s smallest satellite-carrying rocket?'),
  ('2018',141,E'23 writers have been selected for the Sahitya Akademi Bal Sahitya Puraskar 2018. Who among them was selected for the Rajasthani language?'),
  ('2018',142,E'Match the dynasties with their capitals:\nDynasties\nA. Shunga\nB. Satavahana\nC. Kadamba\nD. Chandela\nCapital\ni. Mahoba\nii. Banavasi\niii. Paithan\niv. Pataliputra\nChoose the correct codes:'),
  ('2018',143,E'Which of the following statements about temple architecture are true?\n(i) The freestanding temples (made of mortar & stone) are believed to have originated in the Gupta period.\n(ii) The Lad Khan temple, one of the earliest, belongs to the Chalukyas of Badami.\n(iii) In Khajuraho temples, all compartments are connected both internally and externally.\n(iv) The Kailashnath temple at Kanchi is the earliest freestanding temple of the Dravidian style.\nChoose the correct answer:'),
  ('2018',144,E'Which one of the following statements is not true about the Shreni system of Ancient India?'),
  ('2018',145,E'Who created the department of Diwan-i-Arz in the Delhi Sultanate?'),
  ('2018',146,E'The main seat (Peeth) of the Varkari sect is situated at:'),
  ('2018',148,E'Which of the following pairs of institution and founder is not correctly matched?'),
  ('2018',149,E'Which revolutionary was not involved in the Hardinge Bomb incident?'),
  ('2018',150,E'Who played the role of mediator in the Gandhi-Irwin Pact?'),
  ('2021',1,E'Which of the following statement regarding Ruma Devi is not true?'),
  ('2021',2,E'The Saints named Bakhnaji, Sant Das Ji, Jagannath Das and Madho Das were associated with which of the following Sect?'),
  ('2021',3,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I (Festival) | List-II (Date/Month of celebration) |\n| :--- | :--- |\n| (A) Kajli Teej of Bundi | (i) The third of Bhadrapad Krishna |\n| (B) Holi | (ii) Full moon day of Phalgun |\n| (C) Paryushan Parva | (iii) Bhadrapad Month |\n| (D) Gangaur | (iv) Chaitra Month |\nCode -'),
  ('2021',4,E'Which of the following Doctrines are associated with Jainism?\n(i) Anekantavada\n(ii) Sarvastivada\n(iii) Sunyavada\n(iv) Syadvada\nSelect the correct answer using the code given below-'),
  ('2021',5,E'What is ''Aanau'' in social customs and traditions of Rajasthan?'),
  ('2021',6,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I | List-II |\n| :--- | :--- |\n| (A) Howrah Conspiracy case | (i) Master Ami Chand (Amir Chand) |\n| (B) Lahore Conspiracy case | (ii) Arvind Ghosh |\n| (C) Delhi Conspiracy case | (iii) Jatindranath Mukherjee |\n| (D) Alipore Conspiracy case | (iv) Rajguru |\nCode -'),
  ('2021',7,E'The Rajamundri Social Reform Association to encourage widow re-marriage was founded in 1871 by -'),
  ('2021',8,E'When and with whose efforts was Indian Institute of Science established in Bangalore?'),
  ('2021',9,E'Name the revolutionary woman, who participated in the Peasant Movement of Bijoliya and was arrested. She also participated in 1930 Satyagrah and 1932 Civil Disobedience Movement and was sentenced to Jail -'),
  ('2021',10,E'Match list-I with list-II and choose the correct answer from the code given below-\n| List-I (Tirthankara) | List-II (Their cognition) |\n| :--- | :--- |\n| (A) Parshvanath | (i) Bull |\n| (B) Adinath | (ii) Lion |\n| (C) Mahaveer | (iii) Snake |\n| (D) Shantinath | (iv) Deer |\nCode -'),
  ('2021',11,E'Bhatiyani Pratapkunwari, the queen of Jodhpur King Mansingh got the temple reconstructed elsewhere as the earlier one had caved in. She got the temple consecrated in 1857. The name of the temple is -'),
  ('2021',12,E'Among Mauryan idols, the idol inscribed with the name Manibhadra (Yaksha) was found from which place?'),
  ('2021',13,E'During the Quit India Movement, a girl named Kanaklata Barua led a public procession and defying the police, tried to enter the police station but was shot dead. This incident took place at -'),
  ('2021',14,E'Which one of the following pair is not correctly matched?\nBooks - Authors\n(A) Neh Tarang - Sawai Pratap Singh\n(B) Nagdaman - Sayanji Jhula\n(C) Ranmal Chhand - Shridhar Vyas\n(D) Bhasha Bhushan - Maharaja Jaswant Singh'),
  ('2021',15,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I | List-II |\n| :--- | :--- |\n| (A) Vrihi | (i) Sugarcane |\n| (B) Mudga | (ii) Rice |\n| (C) Yava | (iii) Mung bean |\n| (D) Ikshu | (iv) Millet |\nCode -'),
  ('2021',16,E'Varika Vishnuvardhan Victory Tower situated in Bayana Fort belongs to which period?'),
  ('2021',17,E'Consider the following statements pertaining to the Ahar Civilization -\n(A) The natives of Ahar knew copper smelting.\n(B) Rice was unknown to them.\n(C) Metal work was one of the means of economy of the Ahar.\n(D) Black Red coloured pottery have been found here, on which generally white coloured geometrical designs have been carved.\nChoose the correct option -'),
  ('2021',18,E'When and where was the Central Electrochemical Research Institute established with the efforts of Alagappa Chettiar, Dr Shanti Swaroop Bhatnagar and Pt. Jawahar Lal Nehru?'),
  ('2021',19,E'On which part of body ''Toti'' ornament is worn?'),
  ('2021',20,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I | List-II |\n| :--- | :--- |\n| (A) The Battle of Gagron | (i) 1519 AD |\n| (B) The Battle of Sarangpur | (ii) 1544 AD |\n| (C) The Battle of Summel | (iii) 1437 AD |\n| (D) The Battle of Saheba | (iv) 1541-42 AD |\nCode -'),
  ('2021',21,E'Where in Rajasthan, the printing press ''Vedic Yantralaya'' was established?'),
  ('2021',22,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I (Folk Musical Instrument) | List-II (Famous Music Artist) |\n| :--- | :--- |\n| (A) Bhapang | (i) Sadiq Khan |\n| (B) Nad | (ii) Zahoor Khan |\n| (C) Algoza | (iii) Karna Bheel |\n| (D) Khartal | (iv) Ramnath Choudhary |\nCode -'),
  ('2021',23,E'Consider the following statements and choose the correct answer using the code given below\nStatement 1: Krishnadevaraya, ruler of Vijaynagar wrote the treatise Amuktamalyada.\nStatement 2: Krishnadevaraya is also known by the name of Andhra Bhoj.\nStatement 3: Allasani Peddana, the poet laureate well versed in Sanskrit and Tamil, adorned his court.\nCode -'),
  ('2021',24,E'Where is the Rajasthani Bhasha, Sahitya and Sanskriti Academy located?'),
  ('2021',25,E'Where and when was the newspaper ''Mazharul - Saroor'' published?'),
  ('2021',26,E'The correct sequence of Chief Justice of Supreme Court of India is -'),
  ('2021',27,E'Which of the following statement about resolution adopted by a State Legislative Assembly under Article 169 of the Constitution of India for the abolition of the State Legislative Council is correct?'),
  ('2021',28,E'According to the ''Rules of Procedure and Conduct of Business in Rajasthan Legislative Assembly'', which of the following department''s estimates do not comes under the control of Estimates Committee ''A''?'),
  ('2021',29,E'Rajasthan Public Service Commission presents its annual report to -'),
  ('2021',30,E'According to the provisions of the Rajasthan Municipal Act, 2009, maximum number of persons that can be nominated by the State Government in Municipal Council is -'),
  ('2021',31,E'Which one of the following is not basic element of the citizen charter?'),
  ('2021',32,E'In which of the following year, for the first time Rajasthan Administrative Service Officers were posted as District Collector?'),
  ('2021',33,E'Which of the following Chief Ministers of Rajasthan have not been the member of Lok Sabha?\n(A) Hari Dev Joshi\n(B) Bhairon Singh Shekhawat\n(C) Tika Ram Paliwal\n(D) Barkatullah Khan\nCorrect answer is'),
  ('2021',34,E'Who among the following is eligible to be appointed as the Chairperson of Rajasthan State Human Rights Commission?'),
  ('2021',35,E'Which Section of the Rajasthan Panchayati Raj Act, 1994 has been amended to replace the expression ''Gram Vikas Adhikari'' in place of ''Gram Sevak''?'),
  ('2021',36,E'Assertion (A): The Duty of Comptroller and Auditor General is not merely to ensure the legality of expenditure but also its propriety.1\nReason (R): He has to uphold the Constitution and the Laws of Parliament in the field of financial administration2.'),
  ('2021',39,E'Under Article 103 of the Constitution of India, the President shall obtain the opinion of which of the following authority before giving any decision on any question regarding the disqualification of the members of the Lok Sabha?'),
  ('2021',40,E'Which Constitutional Amendment Act dealing with National Judicial Appointments Commission, was declared unconstitutional by the Constitution Bench of the Supreme Court?'),
  ('2021',41,E'Which feature of Chief Minister Chiranjeevi Health Insurance Scheme is incorrect?'),
  ('2021',42,E'Consider the following statements regarding State Election Commission, Rajasthan -\n(i) The State Election Commission, Rajasthan was constituted in December, 1994.\n(ii) It has a Secretary who is also the Chief Electoral Officer for the state.\nCode:'),
  ('2021',44,E'The case of Vishakha and others Vs. State of Rajasthan and others is related to -'),
  ('2021',45,E'Gurumukh Nihal Singh was appointed as the first Governor of Rajasthan on -'),
  ('2021',46,E'Fundamental Duties were incorporated in the Constitution on the recommendation of -'),
  ('2021',47,E'Who among the following Judges of Rajasthan High Court has held the office of State Minister in Government of Rajasthan?'),
  ('2021',48,E'Identify the correct pair mentioning the Directive Principles of State Policy in the Constitution of India -'),
  ('2021',49,E'Which one of the following said, "A Constitution, like a machine, is a lifeless thing. It acquires life because of the men who control it and India needs today nothing more than a set of honest men who will have the interest of the country before them"?'),
  ('2021',50,E'Which of the following is not true about the objectives of the Right to Information Act?'),
  ('2021',51,E'In which among the following district, sub-tropical hilly forests are found?'),
  ('2021',52,E'In which year Rajasthan Solar Energy Policy was declared?'),
  ('2021',53,E'Which among the following is not correctly matched?\nLake - Country\n(A) Balkhash - Kazakhstan\n(B) Titicaca - Bolivia-Peru\n(C) Erie - USA-Canada\n(D) Baikal - Ukraine'),
  ('2021',54,E'Which one of the following is not correctly matched?'),
  ('2021',55,E'Gogelav Conservation Reserve is situated in which district?'),
  ('2021',56,E'Match list-I with list-II and select the correct answer using code given below -\n| List-I (Tourist Centre) | List-II (Location) |\n| :--- | :--- |\n| (A) Lalgarh | (i) Jhalawar |\n| (B) Tripura Sundari | (ii) Barmer |\n| (C) Gagron Fort | (iii) Bikaner |\n| (D) Nakoda | (iv) Banswara |\nCode -'),
  ('2021',58,E'As per Koeppen''s climate classification, which among the following are correctly matched?\n(A) Cwg - Bharatpur\n(B) Bwhw - Barmer\n(C) Bshw - Ganganagar\n(D) Aw - Dungarpur'),
  ('2021',59,E'Which among the following are parts of Thar desert?\n(A) Godwar Tract\n(B) Shekhawati Tract\n(C) Banas Plain\n(D) Ghaggar Plain'),
  ('2021',62,E'The second highest percentage of Scheduled tribe population in Rajasthan is found in (2011) -'),
  ('2021',63,E'Which among the following is situated on North-South corridor?'),
  ('2021',64,E'Match list-I with list-II and choose the correct answer from the code given below -\n| List-I (District) | List-II (Main Industry) |\n| :--- | :--- |\n| (A) Udaipur | (i) White cement |\n| (B) Nagaur | (ii) Chemical |\n| (C) Bhilwara | (iii) Textile |\n| (D) Kota | (iv) Lead and Zinc |\nCode -'),
  ('2021',65,E'Match list-I with list-II and choose the correct answer from the code given below-\n| List-I (River) | List-II (Tributary) |\n| :--- | :--- |\n| (A) Godavari | (i) Bhavani |\n| (B) Mahanadi | (ii) Penganga |\n| (C) Damodar | (iii) Seonath |\n| (D) Kaveri | (iv) Barakar |\nCode -'),
  ('2021',66,E'Which among the following is correctly matched?'),
  ('2021',67,E'Which among the following is correctly matched?\n(A) Mando-ki-pal - Feldspar\n(B) Talwara - Lead and Zinc\n(C) Kherwara - Asbestos\n(D) Rishabhdev - Mica'),
  ('2021',68,E'''Green Energy Corridor'' will pass through which of the following districts of Rajasthan?'),
  ('2021',69,E'Match list-I with list-II and choose the correct answer from the code given below-\n| List-I (Site) | List-II (Energy) |\n| :--- | :--- |\n| (A) Pavagada | (i) Wind |\n| (B) Tattapani | (ii) Solar |\n| (C) Muppandal | (iii) Geo-thermal |\n| (D) Kakrapar | (iv) Atomic |\nCode -'),
  ('2021',70,E'Match list-I with list-II and choose the correct answer from the code given below-\n| List-I (Landform) | List-II (Continent) |\n| :--- | :--- |\n| (A) Aconcagua | (i) Australia |\n| (B) Meseta | (ii) Africa |\n| (C) Serengeti Plains | (iii) Europe |\n| (D) Gibson desert | (iv) South America |\nCode -'),
  ('2021',71,E'What is the rank of India in the World Happiness Index 2021?'),
  ('2021',72,E'What is not included in the Index of Industrial Production (IIP) which is the measure of Industrial activities in the Indian Economy?'),
  ('2021',73,E'What is the proposed plan expenditure in percentage of total expenditure on electricity in Rajasthan''s budget 2021 - 22?'),
  ('2021',74,E'The Net National Product at Market Price (N.N.P. MP) is -'),
  ('2021',75,E'In which of the following budget, the Railway Budget was merged with the Union Budget in India?'),
  ('2021',76,E'Which of the following statement is wrong about Rashtriya Gram Swaraj Abhiyaan in Rajasthan?'),
  ('2021',77,E'''Base year'' in National Income accounting means -'),
  ('2021',78,E'What is the share of Rajasthan Government in funding in National Mission on Agriculture Extension and Technology?'),
  ('2021',79,E'What was the rank of India in the Ease of Doing Business Index for 2019, as per the Doing Business Report (DBR), 2020?'),
  ('2021',80,E'Which of the following department has been declared as the Nodal Department for the effective implementation of Sustainable Development Goals in Rajasthan?'),
  ('2021',81,E'When was the "PM Kisan Maandhan Yojana" launched for the purpose of pension to small and marginal farmers?'),
  ('2021',82,E'According to Rajasthan budget 2021 - 22, in which district the Fintech Digital University will be established?'),
  ('2021',83,E'Atal Bhu-Jal scheme was launched on 1 April, 2020 by Government of India, with assistance of-'),
  ('2021',84,E'Which of the following district is not a part of ''Desert Triangle'' in Rajasthan?'),
  ('2021',85,E'According to census - 2011, what was the work participation rate in India and Rajasthan respectively?'),
  ('2021',86,E'Which of the following is responsible for implementation of "Ayushman Bharat Pradhan Mantri Jan Aarogya Yojana"?'),
  ('2021',87,E'For empowerment of women Indira Mahila Shakti Nidhi was launched on -'),
  ('2021',88,E'As per the advance estimates, per capita income of Rajasthan at constant prices (2011-12) for the year 2020-21 is-'),
  ('2021',89,E'In case of critical illness health insurance covered per family per year under the scheme Ayushman Bharat Mahatma Gandhi Rajasthan Swasthaya Bima Yojana is -'),
  ('2021',90,E'''Parwan'' multipurpose irrigation project of Rajasthan will provide irrigation facilities in the following districts -'),
  ('2021',91,E'With a 16:9 picture aspect ratio, display resolution 1080p means -'),
  ('2021',92,E'The state flower of Rajasthan is -'),
  ('2021',93,E'Full form of MOEMS is -'),
  ('2021',94,E'Malignant malaria is caused by -'),
  ('2021',95,E'Which part of human body is infected by the virus causing Japanese encephalitis?'),
  ('2021',96,E'Compressed Natural Gas (CNG) is mainly -'),
  ('2021',97,E'Kadaknath is a breed of -'),
  ('2021',98,E'How much has the global average temperature risen in the last century?'),
  ('2021',99,E'The State Remote Sensing Application Centre working under Department of Science and Technology Rajasthan is situated at'),
  ('2021',100,E'A quantum dot is'),
  ('2021',101,E'In Stethoscope, the sound of the patient''s heartbeat reaches the doctor''s ears by -'),
  ('2021',102,E'According to India State of Forest Report 2019, in which one of the following district, very dense forest area is minimum?'),
  ('2021',103,E'Mother foetus Rh blood type incapability problems can occur if the mother is ... and her foetus is ...'),
  ('2021',104,E'Trisomy 21 is known as -'),
  ('2021',106,E'The motto of Defence Research and Development Organisation is -'),
  ('2021',107,E'Which of the following is not a Zoonotic disease?'),
  ('2021',109,E'Which of the following frequency bands is not used in INSAT/GSAT satellite communication?'),
  ('2021',110,E'An inverted pyramid of biomass can be found in which ecosystem?'),
  ('2021',111,E'In the following pie chart, the percentage distribution of the expenditure incurred in publishing a book is given - If for a certain quantity of books, the publisher has to pay 22,950 for royalty, then what will be the amount of printing to be paid for the books?'),
  ('2021',112,E'Arithmetic mean of the numbers between 1 to 156 which are divisible by 2, 3, 4 and 6 is -'),
  ('2021',114,E'In a group 6 girls and 4 boys, four children are to be selected. In how many different ways can they be selected such that at least one girl should be there?'),
  ('2021',115,E'When watch shows 7:45 am, the minute hand points towards East. After 3 hours, in which direction does the hour hand point?'),
  ('2021',116,E'A rectangular room is 12 meter long, 6 meter wide and 4 meter high. It has two doors of size 2 meter x 1 meter each and two windows of size 1.5 meter x 1 meter each. If the rate of paint (on the walls) is 15 per square meter, then total cost of painting the walls is -'),
  ('2021',118,E'If on a certain amount, the difference between Compound interest and Simple interest at the rate 5% annual for three years is 183, then the Principal amount is -'),
  ('2021',119,E'A die is rolled three times. The probability of getting a larger number than the previous number each time is -'),
  ('2021',120,E'A bag contains 1, 50 paisa and 25 paisa coins in the ratio 25 : 9 : 5. If total amount in the bag is 2460, then the number of 50 paisa coins in the bag is -'),
  ('2021',121,E'A statement is followed by four arguments numbered I, II, III & IV. Choose which of the argument(s) is/are strong argument(s)?\nStatement: Should the rule of wearing helmet for both driver and pillion rider while driving a motor cycle be enforced strictly?\nArguments:\nI No, each individual knows how to protect his own life and it should be left to his discretion.\nII Yes, it is a rule and rules should be followed strictly by all.\nIII Yes, it is a necessity as the head is most sensitive/controlling organ, it should be protected by the helmet.\nIV No, it does not ensure safety of the head.'),
  ('2021',122,E'Study the following then answer the question -\nStatement: The petrol prices have gone up during the past few weeks.\nCourses of action:\nI The government should set up an expert committee to study the trend of prices.\nII The government should immediately reduce taxes on petrol.\nIII The government should advise the general public to refrain from purchasing petrol for few weeks.1\nDecide which of the suggested course of action follows.2'),
  ('2021',123,E'Virendra is the son of Rajendra''s father. Rajendra''s paternal Aunt is Manju. Adarsh is the husband of Manju and son-in-law of Prakash. How is Prakash related to Rajendra?7'),
  ('2021',124,E'Suppose that in a particular code, TIGER is written as QDFHS and MERIT is written as SHQDL, then in the same code, FROZEN will be written as -12'),
  ('2021',126,E'A statement is followed by two conclusions numbered I & II. You have to assume everything in the statement to be true, then consider the two conclusions together and decide which of them logically follows.\nStatement: Nowadays parents are prepared to pay any fee for an elite education institute for the perfect development of their children.\nConclusions:\nI Parents have an obsessive passion for a perfect development of their children through good education institute.\nII These days all parents are very well off.'),
  ('2021',127,E'A statement is followed by two assumptions numbered I and II. Consider the statement and the following assumptions and decide which of the assumption is implicit in the given statement?\nStatement: Lalita has a large collection of books and she keeps on purchasing new books to add to her collection.\nAssumptions:\nI Lalita has read each and every book that she has purchased.\nII Lalita has love and passion for books.'),
  ('2021',128,E'Given below are two statements, one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Selecting the right man for the right job at the right pay is the right approach.\nReason (R): A wrongly selected man is a liability.\nIn the above context, which one of the following is correct?'),
  ('2021',131,E'India has signed Memorandum of Understanding (MoU) in March 2021, with which of the following countries on cooperation in the field of Disaster Management, Resilience and Mitigation?'),
  ('2021',132,E'Which player was the Indian flag bearer at the closing ceremony of Tokyo Paralympic 2020?'),
  ('2021',133,E'Who has been granted International Eni Award 2020?'),
  ('2021',135,E'Who among the following is the author of the book ''Marathon War: Leadership in combat in Afghanistan''?'),
  ('2021',136,E'Who is the author of the book "Sanskriti Ri Sanatan Deeth"?'),
  ('2021',137,E'Rajasthan Jan Aadhar Authority Ordinance came into force on -'),
  ('2021',138,E'Read the following statements about Supply Chain Resilience Initiative (SCRI) -\n(i) In the context of International trade, supply chain resilience is an approach that helps a country to ensure uninterrupted supply of import in an unexpected situation.\n(ii) This is an initiative of five countries, India is one of them.\nChoose the correct code -'),
  ('2021',139,E'Who among the following won silver medal in Tokyo Olympic 2021? Select the correct answer from code given below -\n(A) Ravi Kumar Dahiya\n(B) P. V. Sindhu\n(C) Bajrang Punia\n(D) Mirabai Chanu\nCode -'),
  ('2021',140,E'Rajasthan government has launched an app to help college students with digital academic materials. What is the name of this app?'),
  ('2021',141,E'"Mission Niryatak Bano" campaign to promote aspiring exporters is launched by -'),
  ('2021',142,E'Tianwen-1 is -'),
  ('2021',143,E'Match list-I with list-II and identify the correct answer from the code given below -\nList-I\n(A) Bhavina Patel\n(B) Nishad Kumar\n(C) Harvinder Singh\n(D) Devendra Jhajharia\nList-II\n(i) Archery\n(ii) Javelin throw\n(iii) Table Tennis\n(iv) High jump\nCode -'),
  ('2021',145,E'''Hunger Hotspots Report'' was released on 23 March, 2021 by -'),
  ('2021',146,E'Who is Najib Mikati?'),
  ('2021',147,E'India''s first farm based "KUSUM" solar power project was commissioned in which village of Rajasthan?'),
  ('2021',148,E'"NABI MG" is -'),
  ('2021',149,E'Why Dholavira (Gujarat) was in news recently?'),
  ('2021',150,E'President Ram Nath Kovind granted assent to which Constitutional Amendment Act on 18th August, 2021?'),
  ('2023',1,E'The East-West Corridor connect to'),
  ('2023',3,E'Which of the following group of districts are correctly arranged in descending order as per the amount of monsoon rainfall they receive?'),
  ('2023',4,E'Which three rivers of the following form ''Triveni'' Sangam ?'),
  ('2023',5,E'As per the India State of Forest Report 2021, the forest cover in terms of vegetation cover is 16,654 square km, it is ________ percent of Rajasthan''s geographical area.'),
  ('2023',7,E'The first sugar industry based on beet-root was established at -'),
  ('2023',8,E'The Mahi Bajaj Sagar Project is a joint venture of -'),
  ('2023',9,E'Choose the district of Rajasthan which had the lowest decadal population growth rate between 2001-2011.'),
  ('2023',10,E'Kalakhuta, Leelwani, Nardiya, Timmamori are producing regions of which mineral in Rajasthan?'),
  ('2023',11,E'Kalisindh Super Thermal Power Station is located at -'),
  ('2023',13,E'Mahi Kanchan and RCB 911 are hybrid variety of -'),
  ('2023',14,E'Consider the following statements regarding the Constituent Assembly of India :\n(i) The final session of the Constituent Assembly was held on 24th January, 1950.\n(ii) Dr. Rajendra Prasad was declared to be duly elected to the office of President of India in this final session.'),
  ('2023',15,E'Which of the following schedule of the Constitution of India was added to the Constitution by the first Constitutional Amendment?'),
  ('2023',16,E'Identify the incorrect statement regarding Judicial Interpretation of Article 21 after Supreme Court''s verdict in Maneka Gandhi Case, 1978.'),
  ('2023',17,E'Nathmal Ji Ki Haveli is located in'),
  ('2023',18,E'Identify the incorrect statement regarding Council of States (Rajya Sabha).'),
  ('2023',20,E'Match the following List P (Directive Principles) with List - R (Articles):\n| List - P | List - R |\n| :--- | :--- |\n| A. Equal justice and free legal aid | I. Article 48 A |\n| B. Protection of the environment | II. Article 39 A |\n| C. Right to Work | III. Article 41 |\n| D. Protection of Monuments | IV. Article 49 |\nSelect correct option:'),
  ('2023',21,E'Which of the following sections of the Right to Information Act is not related to the functions and powers of the Central Information Commission?'),
  ('2023',22,E'Which one of the following Commission did recommend the establishment of an Inter-Government Council in place of Inter-State Council?'),
  ('2023',23,E'Consider the following statements:\n(i) The Lok Sabha Elections of 1989 marked the end of, what Political Scientists have called, the ''Congress System''.\n(ii) Indian National Congress emerged as the single largest party in the 1989 Lok Sabha Elections.'),
  ('2023',24,E'Match the following List-P (CAG) with List-R (Articles):\n| List-P | List-R |\n| :--- | :--- |\n| A. Appointment of CAG | I. Article 148 |\n| B. Duties and Powers of CAG | II. Article 151 |\n| C. Form of Accounts of the Union | III. Article 149 |\n| D. Audit Reports | IV. Article 150 |\nSelect correct option.'),
  ('2023',25,E'Which of the following statement is not correct regarding the Chief Minister of Rajasthan?'),
  ('2023',26,E'What can be the minimum strength of Rajasthan''s Council of Ministers?'),
  ('2023',27,E'In the Presidential Election, 2022, the vote value of each member of Rajasthan Legislative Assembly was -'),
  ('2023',28,E'According to Article 217(1) of the Constitution, a Judge other than the Chief Justice of Rajasthan High Court is appointed by the President after consultation with -'),
  ('2023',29,E'Which of the following recommended the post of Rajpramukh to be abolished in Rajasthan and the arrangement of the Governor was made instead?'),
  ('2023',30,E'Which one of the following is not a part of Rajasthan Urban Drinking Water Sewerage and Infrastructure Corporation Limited?'),
  ('2023',31,E'Through which Amendment Act, the existing, "Village Level Workers'' has been substituted by the ''Gram Vikas Adhikari''?'),
  ('2023',32,E'Consider the following statements regarding Rajasthan Public Service Commission:\n(i) The chairman and members of the commission are appointed by the Governor of Rajasthan.\n(ii) The chairman or any other member of the commission shall only be removed from his office, by order of the President.'),
  ('2023',33,E'Tehsildar is appointed by -'),
  ('2023',34,E'A Committee constituted in 2014 under the Chairmanship of Narpat Mal Lodha is related to which of the following subjects?'),
  ('2023',35,E'Consider the following statements regarding State Election Commission, Rajasthan:\n(i) It was constituted in July, 1994 under Article 243 K of the Constitution of India.\n(ii) It is a single member commission headed by the State Election Commissioner.'),
  ('2023',36,E'In April, 2023, a Bench of Rajasthan State Information Commission is approved by State Government to be established at which city?'),
  ('2023',37,E'Which of the following scheme is associated with slogan "Koi Bhukha Na Soye"?'),
  ('2023',38,E'Consider the following statements regarding Rajasthan State Human Rights Commission:\n(i) Commission has one chairperson and four members in accordance with the provisions of The Protection of Human Rights (Amendment) Act, 2006.\n(ii) At present, Justice Gopal Krishna Vyas is its chairperson.'),
  ('2023',39,E'Which of the following expression shows the formula of Gross Fiscal Deficit?'),
  ('2023',40,E'Which of the following is NOT a Public good?'),
  ('2023',41,E'Consider the following statements regarding inflation:\nStatement (A): Head-line inflation refers to the rate of change in the Consumer Price Index Number, a measure of the average price of a standard basket of goods and services consumed by a typical family.\nStatement (B): Core inflation measures the change in average consumer prices after excluding from the Consumer Price Index certain items of volatile prices such as food and fuel.\nOf these statements,'),
  ('2023',42,E'Consider the following statements regarding Indira Gandhi Urban Employment Guarantee Scheme:5\n(i) It guarantees per year 125 days'' employment for families residing in Urban Areas.6\n(ii) After registration, the eligible candidate has to be provided employment in 30 da7ys.'),
  ('2023',43,E'Which of the following is not a measure of selective credit control?'),
  ('2023',44,E'Which of the following statement, related to Pharmaceutical sector is not correct?'),
  ('2023',45,E'The rank of India in Global Happiness Index 2023 is'),
  ('2023',46,E'Which of the following statement related to automobile sector is not correct?'),
  ('2023',47,E'Which of the following is NOT a tool of fiscal policy?11'),
  ('2023',48,E'As per the advance estimates of the year 2022-23, what percent share is Rajasthan''s GSDP estimated to contribute in India''s nominal Gross Domestic Product (GDP)?'),
  ('2023',49,E'Which of the following statement(s) is/are true for Atal Bhujal Scheme in Rajasthan?\n(a) Atal Bhujal Scheme has been running by Government of Rajasthan with the Financial assistance of Govt. of India.\n(b) The focus of this scheme is on better management of ground water as well as to prevent its reducing level.\nSelect the correct answer from the codes given below :'),
  ('2023',50,E'Which of the following fact is not correct about Mukhya Mantri Laghu Udhyog Protsahan Yojana (MLUPY) of Rajasthan?'),
  ('2023',51,E'In the year 2022-23, contribution of which sub-sector in Gross State Value Added (GSVA) at current prices of service sector of Rajasthan was maximum?'),
  ('2023',52,E'Which sector is likely to show highest increase in the real GSVA (Gross State Value Added) at constant basic prices (2011-12) in the year 2022-23 over previous year?'),
  ('2023',53,E'Which agency is funding upgradation of 801 km of 11 state highways in Rajasthan State Highways Development Program-II project?'),
  ('2023',54,E'In Rajasthan, which agency is entrusted with the responsibility of implementation of PM-KUSUM Yojana (component A) i.e. installation of small solar power plants of 0.5 MW to 2 MW capacity?'),
  ('2023',55,E'In Rajasthan, the Energy Conservation Day is celebrated on'),
  ('2023',56,E'Government of Rajasthan enacted the Rajasthan Fiscal Responsibility and Budget Management (FRBM) Act in year'),
  ('2023',57,E'In which of the following scheme, the main objective is to promote the use of appropriate methods, care and services during pregnancy, safe delivery and lactation period to improve the health and nutritional status of pregnant and lactating women and their infants (0-6 months)?'),
  ('2023',58,E'Which of the following options indicate one of the important objectives of (Indira Mahila) Shakti Udaan Scheme?'),
  ('2023',59,E'Which among the following is a Narcotic analgesic drug?'),
  ('2023',60,E'Myopia and Hypermetropia can be respectively corrected by'),
  ('2023',61,E'Which of the following scheme is an attempt to make rural areas socially, economically and physically sustainable regions?'),
  ('2023',62,E'Arrange the following units of measure for digital information into correct order, starting with the smallest unit first and going to the largest unit:\na. Kilobyte\nb. Byte\nc. Megabyte\nd. Terabyte\ne. Gigabyte\nf. Bit'),
  ('2023',63,E'On 23rd August 2023, LCA (Light Combat Aircraft) Tejas successfully test fired ASTRA missile, this missile is'),
  ('2023',64,E'Satellites TELEOS-2 and Lumelite-4 were launched in April 23 from Sriharikota by the launcher'),
  ('2023',65,E'If in a material one dimension is reduced to the Nano range while the other two dimensions remain large, the structure so obtained is known as'),
  ('2023',66,E'Which of the following file format is not a video file format?'),
  ('2023',67,E'Choose wrong statement regarding proteins:'),
  ('2023',68,E'The Red Blood cells of a person with Blood group ''O'' contains Agglutinogen:'),
  ('2023',69,E'Which one of the following diseases is not a bacterial disease?'),
  ('2023',70,E'Species of Plasmodium which causes Malignant Malaria :'),
  ('2023',71,E'NTU is the unit for measuring'),
  ('2023',72,E'Which of the following do not grow in polluted area?'),
  ('2023',73,E'Rajiv Gandhi Centre for Biotechnology is situated at'),
  ('2023',74,E'Out of total Oxygen present in the earth''s atmosphere, the estimated production of oxygen by Amazon forest through photosynthesis is'),
  ('2023',75,E'National Research Centre on camel is located at'),
  ('2023',76,E'Which one of the following is a group of millet crops?'),
  ('2023',77,E'Which of these companies is established by Government of Rajasthan with the aim to regulate developing needs of Information Technology skills in 21st century?'),
  ('2023',78,E'A bill was passed by Rajasthan Assembly in 2023 to establish second Rajasthan Veterinary and Animal Sciences University at'),
  ('2023',79,E'Which of these natural resources is considered as non-renewable resource?'),
  ('2023',80,E'A statement is followed by two arguments I and II. Choose which of the argument/s is/are strong:\nStatement: Should all diesel engines be replaced by electric engines in trains?\nArguments:\nI. Yes, diesel engine causes a lot of pollution.\nII. No, India does not produce enough electricity to fulfil even the domestic needs.'),
  ('2023',81,E'A statement is followed by two assumptions I and II. Consider the statement and the following assumptions and decide which of the assumption/s is/are implicit in the given statement:\nStatement: If it does not rain throughout this month, most of the farmers would be in trouble this year.\nAssumptions:\nI. Timely rain is essential for farming.\nII. Most of the farmers are generally dependent on rains.'),
  ('2023',83,E'A statement is followed by two conclusions I and II. You have to assume everything in the statement to be true, then consider the two conclusions and decide which of them logically follows:\nStatement: After joining, Municipal Commissioner told to people of city "A" - "My first and foremost task is to beautify this city like Indore."\nConclusions:\nI. The people of city "A" are not aware about the present condition of the city.1\nII. The Commissioner has worked in Indore and has good experience of beautifying cities.2'),
  ('2023',85,E'In a certain code language, ABONDONMENT is written as DNOBAOTNEMN and ESTABLISHED is written as BATSELDEHSI. Then in the same code language, GERMINATION will be written as ?'),
  ('2023',86,E'A family has eight members. E is the mother of F and G. A is the son-in-law of E. C is the daughter of G. D is the maternal grandfather of C. D has one son and one daughter. H is the sister-in-law of G. B is the niece of F. How is F related to A?'),
  ('2023',88,E'Seven persons P, Q, R, S, T, U and V are sitting in a row. T and U have one person in between them. V is immediate right to P. Q is immediate left to U. There is one person between S and P. S is not the neighbour of V. V and U have two persons between them. R is immediate left to P. Which person is sitting exactly in the middle of the row?'),
  ('2023',89,E'Images of consonants of the capital English alphabets are observed in a mirror. What is the number of images of these which look like their original shapes?'),
  ('2023',90,E'A solid cube has been formed with 64 smaller cubes. How many smaller cubes will not be visible in any condition?'),
  ('2023',91,E'Three students A, B and C of a school receive cash prize in the ratio 3: 4: 5 in a competition. Then the school principal gives Rs. 4,000 to each student. As a result now the cash prize of A, B and C becomes in the ratio 5: 6:7. How much did B get in the competition?'),
  ('2023',93,E'In a group of 400 boys, each boy plays at least one of the games cricket, hockey and football. 185 play cricket, 165 play hockey and 160 play football. 40 boys play only cricket and football. 20 boys play only hockey and cricket. 10 boys play only hockey and football. How many boys play all the three games?'),
  ('2023',95,E'Following table shows runs scored by four batsmen in both innings of a test match. Who is the fastest run scorer in the test match?\n| Batsman | First Inning Runs scored | First Inning Balls faced | Second Inning Runs scored | Second Inning Balls faced |\n| :--- | :--- | :--- | :--- | :--- |\n| P | 79 | 91 | 56 | 154 |\n| Q | 05 | 12 | 50 | 85 |\n| R | 14 | 76 | 61 | 99 |\n| S | 37 | 50 | 13 | 55 |'),
  ('2023',96,E'If the median A and mode B of following distribution satisfy the relation 7(B-A)=9C, then find the value of C:\n| Class | 0-30 | 30-60 | 60-90 | 90-120 |\n| :--- | :--- | :--- | :--- | :--- |\n| Frequency | 4 | 5 | 7 | 4 |'),
  ('2023',99,E'As per a notification issued recently by the Department of Forest, Environment and Climate Change of Rajasthan, how many wet-lands are there in the State?'),
  ('2023',100,E'Where will the "Artificial Intelligence of Things Innovation Hub" be established in the Rajasthan?'),
  ('2023',101,E'The National Tiger Conservation Authority has accorded the fifth tiger reserve in Rajasthan at'),
  ('2023',102,E'In which of the following cities India''s first 3D printed post office has been inaugurated recently?'),
  ('2023',104,E'Which of the following institutions launched a centralised Web Portal ''UDGAM'' recently?'),
  ('2023',105,E'Read the following statements carefully:\nStatement 1: According to TIME Magazine, S.S. Rajamouli has been named among the top "Pioneers" of 2023, while Shahrukh Khan has been named among the top "Icons" of 2023.\nStatement 2: The TIME Magazine''s 100 most influential people list has been divided into six major categories: Leader, Titan, Pioneer, Artist, Icon and Innovator.\nSelect the correct option among the following:'),
  ('2023',106,E'United Nation''s General Assembly has recently elected Dennis Francis to serve as President of its 78th session. He belongs to which of the following countries?'),
  ('2023',107,E'In July 2023, a new variety of urea was launched by the Prime Minister of India at Sikar, Rajasthan. What is the name of this new variety of urea ?'),
  ('2023',108,E'To identify practical applications of artificial intelligence, "AI for Good Global Summit 2023" was recently held in which of the following countries?'),
  ('2023',109,E'Which of the following personalities has been nominated for the Sahitya Academy Yuva Puraskaar 2023 for the Rajasthani language?'),
  ('2023',110,E'India''s first ever outdoor Museum ''Shaheedi Park'' has been recently inaugurated in which city?'),
  ('2023',111,E'Recently the Ecuadorians have made a historic decision by rejecting, oil drilling by a referendum in which of the following biodiverse regions of Amazon?'),
  ('2023',113,E'9th India Region Conference'' of the Common Wealth Parliamentary Association was held in which of the following cities?12'),
  ('2023',114,E'What position is achieved by India in the medal tally of FISU World University Games 2023?'),
  ('2023',115,E'India defeated Malaysia in the final of Fourth Asian Champions Trophy of Hockey on 12th August, 2023. In which stadium this match was played?'),
  ('2023',116,E'Rajeshwari Kumari, who stood fifth in the recently held World Championship at Baku, Azerbaijan, has qualified for the Paris Olympics. She is related to which of the following sports?'),
  ('2023',117,E'India''s Kamaljeet clinched Gold Medal on 24th July, 2023 in Men''s individual 50 metre Pistol Event at ISSF Junior Shooting World Championship 2023. In which of the following countries was the event held ?'),
  ('2023',118,E'Recently C.A. Bhavani Devi of India won a Bronze Medal in the Asian Fencing Championship. She lost to player of which country in the Semi-final?'),
  ('2023',119,E'Which institution in India has been selected for Gandhi Peace Award 2021?'),
  ('2023',120,E'In the excavation of which of the following ancient site the huge collection of iron materials is found related to Malava Republic?'),
  ('2023',121,E'The brave Chauhan ruler of Ajmer who conquered Delhi and annexed it in his kingdom was -'),
  ('2023',122,E'The Arab traveller Suleman visited India in the reign of Pratihar King -'),
  ('2023',123,E'With which of the following Prajamandal Movement Kanhaiya Lal Mittal, Mangilal Bavya and Makbul Alam were associated?'),
  ('2023',124,E'When was Matsya Sangh merged into Vrihat Rajasthan?'),
  ('2023',125,E'In which Rajput Thikana Moti Lal Tejawat was working on the post of Kamdar prior to launching the Aki Movement?'),
  ('2023',126,E'What is the similarity between Jharol (Udaipur), Kurada (Nagore) and Sabania (Bikaner)?'),
  ('2023',127,E'The renowned artist Muhammed Shah was a court artist (Painter) of which Maharaja of Jaipur?'),
  ('2023',128,E'The men of which sect of Rajasthan perform the Agni Dance (Fire dance)?'),
  ('2023',129,E'The names of how many local dialects are mentioned in the Katha collection called Kuvlayamala?'),
  ('2023',130,E'The author of ''Achaldas Khichi re Vachanika'' is'),
  ('2023',131,E'Which of the following is wrongly matched?'),
  ('2023',132,E'The Chandrabhaga fair is held every year in the month of Kartik at-'),
  ('2023',133,E'Which of the following fort of Rajasthan is not a Giri Fort?'),
  ('2023',134,E'Who among the following discovered ''Surkotda'', a site of Harappan culture?'),
  ('2023',135,E'In which dynasty did Chandragupta II marry his daughter Prabhavati and strengthened his position?'),
  ('2023',136,E'The Stupa of Bharhut is a fine example of -'),
  ('2023',137,E'The author of ''Lalit Vigraharaj'' drama was -'),
  ('2023',138,E'Which of the following poet was given the title of ''Andhra Kavita Pitamah'' by Krishnadev Ray?'),
  ('2023',139,E'In which of the following palace built by Akbar in Fatehpur Sikri the Buddhist architecture was followed?4'),
  ('2023',140,E'Who was appointed first Raj Pramukh of Rajasthan?10'),
  ('2023',141,E'Gopal Krishna Gokhale founded Servants of India Society in the year'),
  ('2023',142,E'Who was the President of the special session of Indian National Congress held in Calcutta in September, 1920 in which the resolution of Non-Cooperation Movement was passed?'),
  ('2023',143,E'Which of the following were the members of State Reorganisation Commission formed by Indian Government in August, 1953?14\n(i) Sir Tej Bahadur Sapru15\n(ii) Justice Fazal Ali16\n(iii) K.M. Pannikar17\n(iv) Hridayanath Kunjaru18\nSelect the correct answer by using the code given below:'),
  ('2023',144,E'In which sea do river Elbe and river Rhine drain their water?'),
  ('2023',145,E'The spread of which of the following Sufi sect was mostly limited to Sindh, Multan and Punjab?'),
  ('2023',146,E'The problem of desertification is least in which of the following continents?'),
  ('2023',147,E'Consider the following statements:\nA. The Kashmir Himalayas are famous for ''Karewa'' formations.\nB. Nalagarh Dun is the largest of all Duns.\nC. Namcha Barwa mountain peak is located in Arunachal Himalayas.\nD. ''Valley of Flowers'' is situated in Himachal and Uttarakhand Himalayas.\nCode:'),
  ('2023',148,E'Which areas of India receive rainfall from North-East Monsoon?\nA. Tamil Nadu Coast\nB. Gujarat Coast\nC. Southern Andhra Pradesh\nD. South-East Karnataka\nCode:'),
  ('2023',150,E'Among the following which is not an Industrial Region of U.S.A.?'),
  ('2024',1,E'The four segments of the Golden Quadrilateral join the following cities:\nA. Delhi - Mumbai\nB. Mumbai - Chennai\nC. Chennai - Kolkata\nD. Kolkata - Delhi\nConsider the length of the above segments in descending order and select the correct answer using the codes given below :'),
  ('2024',2,E'Consider the following statements:\nA. Luni Basin and Shekhawati region are the Sub-regions of Rajasthan Bangar.\nB. Ghaggar Plain covers mostly Hanumangarh and Ganganagar district.\nC. Nagaur uplands have salty lakes and inland drainage.\nD. Aravalli ranges are rich in all types of minerals.\nSelect the correct answer using the codes given below:'),
  ('2024',3,E'Which of the following group of districts of Rajasthan is correctly arranged in ascending order as per average rainfall during South-West Monsoon?'),
  ('2024',4,E'Which is not a correct match?\nNuclear Power Plant - State'),
  ('2024',5,E'Which type of soil is dominant in Jaipur, Dausa and Alwar districts?'),
  ('2024',6,E'In the year 2021-22, contribution of Rajasthan in total production of Bajra in the country (in percentage) was :'),
  ('2024',7,E'Medtech Medical Devices Park is located at'),
  ('2024',8,E'In which district of Rajasthan ''Khadin'' is a popular method of water conservation?'),
  ('2024',10,E'At which of the following places, asbestos mines are located in Rajasthan?'),
  ('2024',11,E'The most important resources of lignite in Rajasthan are located at'),
  ('2024',12,E'Which is not a correct match?\nConservation Reserve (as on May 2023) - District'),
  ('2024',13,E'Mount Abu and Ranakpur are included in which tourist circuit?'),
  ('2024',14,E'The national executive of which political party called for the dissolution of the Constituent Assembly and its re-election by adult suffrage?'),
  ('2024',15,E'The correct descending order of districts in Rajasthan based on total literacy rate (census 2011) is'),
  ('2024',16,E'Fundamental Rights provided by which of the following groups of Articles are granted only to ''Citizens'' of India?'),
  ('2024',17,E'In which year it was inserted in the Constitution of India that the State shall secure free legal aid to any citizen by reason of economic or other disabilities?'),
  ('2024',19,E'Which of the following statement is incorrect regarding the election of the President of India?'),
  ('2024',20,E'Identify the correct statement regarding the Election Commission of India.'),
  ('2024',22,E'Which of the following is a matter on which the Finance Commission notified by the Ministry of Finance on 31st December, 2023 shall not make its recommendation?'),
  ('2024',24,E'The Central Vigilance Commission was formed on the basis of the recommendations of which of the following committee?'),
  ('2024',25,E'Which of the following Chief Minister faced President''s Rule in Rajasthan for maximum number of times?'),
  ('2024',26,E'As of the end of the November 2024, how many women were there in the Rajasthan Council of Ministers?'),
  ('2024',27,E'Which of the following statement is incorrect regarding subordinate legislation in Rajasthan Legislative Assembly?'),
  ('2024',28,E'Which of the following statement is not correct regarding the Governor of Rajasthan?'),
  ('2024',29,E'Who becomes the chairperson of District Planning Committee in Rajasthan?'),
  ('2024',30,E'By which Act, the Jaipur Development Authority was established?'),
  ('2024',31,E'Which of the following group of princely states had enacted legislations on Panchayats prior to independence?'),
  ('2024',32,E'Which Article of the Constitution prescribes mandatory consultation with RPSC on disciplinary matters affecting a person serving under Government of Rajasthan?'),
  ('2024',33,E'From which of the following date Pramil Kumar Mathur assumed the office of the Registrar General of Rajasthan High Court?'),
  ('2024',34,E'Under Section 7 of the Rajasthan Lokayukta and Deputy Lokayukta Act, 1973, the Lokayukta is empowered to investigate allegations against ministers and public servants in certain cases. Which of the following subject is not part of those investigations?'),
  ('2024',35,E'What is the amount of security deposit to contest the election of a Mayor by a candidate belonging to the general category?'),
  ('2024',36,E'State Information Commissioner is appointed by the Governor on the recommendation of a Committee. Who of the following is not a member of this Committee?'),
  ('2024',37,E'Among the following Chairpersons of Rajasthan State Human Rights Commission, who could complete a five year term?'),
  ('2024',38,E'The aim of citizen''s charter is not'),
  ('2024',39,E'In which of the following year annual growth rate of Gross National Income and Net National Income on both current prices and constant prices were Negative in India?'),
  ('2024',40,E'Which of the following statement is related to the benefit of the "Input Tax Credit Mechanism" of GST?'),
  ('2024',42,E'Which of the following statements is/are correct in respect of inflation in India?\nA. Core inflation include the prices of food and energy.\nB. Headline inflation exclude food inflation.\nC. Headline inflation is more volatile in nature than core inflation.\nSelect the answer using the codes given below :'),
  ('2024',44,E'Consider the following statements regarding "National Food Security Act" (NFSA) in India:\nA. It was enacted on July 5, 2013.\nB. Around 50 crore persons have been covered under NFSA at present.\nC. The Act legally entitles upto 75% of the rural population and 50% of the urban population to receive subsidized food grains.\nChoose the correct option using codes:'),
  ('2024',45,E'Consider the following statements regarding World Happiness Report 2024:\nA. India ranked 126th out of more than 140 countries, which is lower than its neighbouring countries including China, Nepal, Pakistan, Myanmar, Sri Lanka and Bangladesh.\nB. India''s ranking has remained relatively stagnant over the years, indicating limited progress in improving the overall happiness and well-being of its population.\nSelect the correct answer using the codes given below :'),
  ('2024',46,E'Worker to Population Ratio (WPR) is defined as'),
  ('2024',47,E'Which of the following is not associated with financial sector reforms in India initiated after 1991?'),
  ('2024',48,E'Consider the following statements regarding fiscal deficit of Rajasthan:\nA. The actual fiscal deficit in the year 2022-23 has been 3.76 percent of the State GDP.\nB. This is less than the limit prescribed by the F.R.B.M. Act, 2005.\nC. The fiscal deficit of 2022-23 was higher than that of 2021-22.\nChoose the correct option:'),
  ('2024',49,E'Consider the following statements regarding targets of Rajasthan Mineral Policy - 2024:\nA. Provide employment to 50 lakh people by 2029-30 and over 1 crore people (direct and indirect) by 2046-47.\nB. Enhance the mineral sector''s contribution to state''s GSDP from 3.4 percent in 2023-24 to 5 percent by 2029-30 and to 8 percent by 2046-47.\nC. Expand the number of minerals under extraction from 58 to 70 by 2047.\nWhich of the above statements are correct?'),
  ('2024',50,E'The correct share of various sector in Gross Fixed Capital Formation of Rajasthan in descending order is'),
  ('2024',51,E'Ease of Doing Business ranking for the states in India is released by'),
  ('2024',52,E'Which of the following has been formed in place of Chief Minister''s Rajasthan Economic Transformation Advisory Council (CMRETAC)?'),
  ('2024',53,E'Which of the following park/zone has not been developed by RIICO in Rajasthan?'),
  ('2024',57,E'Who among the following are eligible for Aastha Scheme in Rajasthan?'),
  ('2024',58,E'Mukhyamantri Svanidhi Yojana of Rajasthan aims to'),
  ('2024',59,E'In cataract the natural lens becomes cloudy because of change in which of the following?'),
  ('2024',60,E'Which of the following are units of the pressure?\n(A) bar\n(B) Pa\n(C) torr\n(D) atm\nChoose the correct option:'),
  ('2024',61,E'The main objective of "Rajasthan Urban Sector Development Programme (Phase-III)" is :'),
  ('2024',62,E'Among the following layers, identify the one which is used for wireless connection in IoT devices:'),
  ('2024',63,E'What is the name of the man-portable air defence system developed by ''DRDO'' to neutralize aerial threats?'),
  ('2024',64,E'Which of the following statement is incorrect for Active Electronically Scanned Array Radar (AESA)?'),
  ('2024',65,E'The fourth generation biofuels are obtained from genetically modified:'),
  ('2024',66,E'Regarding Artificial Intelligence (AI), identify the correct statements using the codes given below :\nA. Machine learning is a subset of AI.\nB. Supervised learning involves training a computer system without labelled input data.\nC. Machines learn through trial and error, receiving rewards during reinforcement learning.\nCodes:'),
  ('2024',67,E'Kwashiorkor, a form of malnutrition, is caused by deficiency of which of the following?'),
  ('2024',68,E'Which of the following artificial sweeteners have the highest sweetness value in comparison to sucrose?'),
  ('2024',69,E'Which of the following is a micro-mineral found in human body fluids/tissues?'),
  ('2024',70,E'Select the incorrect set of "the typical Vector - Disease - Type of Pathogen".'),
  ('2024',71,E'According to Central Pollution Control Board, the Air Quality category for IND-AQI range of 101 - 200 is'),
  ('2024',72,E'Select the incorrect statement from the following:'),
  ('2024',73,E'India''s first Nano-cellulose plant developed by ICAR - CIRCOT Mumbai is related to'),
  ('2024',74,E'Red List of IUCN is known as'),
  ('2024',75,E'Select the incorrect statement regarding the Rajasthan Forestry and Biodiversity Project (Phase-2).'),
  ('2024',76,E'Match Column-I (Location of the Center of Excellence) with Column-II (the horticultural crop) and select the correct answer using the codes given below:\nColumn-I\nA. Bassi\nB. Sagra Bhojka\nC. Devrawas\nD. Khemri\nColumn-II\n(i) Mango\n(ii) Custard-apple\n(iii) Pomegranate\n(iv) Guava\n(v) Date-palm\nCodes:'),
  ('2024',77,E'Which Sustainable Development Goal (SDG) under 17 global goals given by United Nations specifically focuses on "Life on Land", aiming to protect, restore and promote sustainable use of terrestrial ecosystems?'),
  ('2024',78,E'"Ganga", India''s first cloned cow born in March 2023 belongs to which breed?'),
  ('2024',79,E'In the question given below, a statement and two assumptions (I) and (II) are given. Choose the correct option from the following:\nStatement: In order to replenish the nutrients in the soil, it is important to grow different types of crops in every alternate season.\nAssumptions:\n(I) A crop can never be grown for the second time in the same field.\n(II) If a different crop is grown in the successive season, no additional nutrients such as fertilizers are required to be added to the soil at all.'),
  ('2024',80,E'Which of the following villages of Rajasthan is transforming itself to a zero-waste model with the help of Green Technology intervention?'),
  ('2024',81,E'In the question given below, three statements are followed by two conclusions numbered (I) and (II). You have to take the given statements to be true. Read the conclusions and given the answer.\nStatements:\nSome symbols are figures.\nAll symbols are graphics.\nNo graphic is a picture.\nConclusions:\n(I) Some graphics are figures.\n(II) Some symbols are pictures.'),
  ('2024',82,E'A statement is followed by two arguments (I) and (II). Choose which of the argument(s) is/are strong.\nStatement: Should every house use solar energy in order to reduce the need of electricity in Rajasthan?\nArguments:\n(I) Yes, it will conserve our natural resources and it will promote environmental compatibility.\n(II) No, solar panels are costly and all the house owners cannot afford it without subsidy.'),
  ('2024',83,E'Eight equidistant points lie on a circle. Using these points as vertices, right angled triangles are drawn such that one side of each triangle is diameter of the circle. The number of such possible right angled triangles is:'),
  ('2024',84,E'Next term in the following sequence is : 2, 12, 36, 80, 150, ?'),
  ('2024',85,E'In a coding system, ''PROJECT'' is written as ''CEOPRT'' and ''PLANE'' is written as ''ELNP''. Then, in the same coding system the ''ORGANISED'' will be written as:'),
  ('2024',86,E'In the question given below, a statement is followed by two courses of action numbered (I) and (II). Choose the correct option from the following:\nStatement: There has been less voting in this Lok Sabha election as compared to previous Lok Sabha election.\nCourse of action:\n(I) The election commission should announce re-election for Lok Sabha.\n(II) Election commission should cancel the voting rights of the people who did not vote in this Lok Sabha election.'),
  ('2024',89,E'Images of consonants of the English alphabet (capitals) are observed in a mirror. What is the number of images which do not look like their original shapes?'),
  ('2024',90,E'A, B, C, D, E and F are six members of a family. B is married to C. F is the mother of E and D is the daughter of F. A''s daughter is E and C''s son is A. There are two married couples in the family. Which of the following is correct?'),
  ('2024',91,E'A housewife has 1000 ml of mixture that contains milk and water in the ratio of 3:1. She adds 250 ml of mixture of milk and water in the ratio of 3:2 in it. Then she uses 250 ml of the combined mixture to make curd. How much of pure milk is left in the mixture remained?'),
  ('2024',92,E'A reduction of 21% in the price of rice enables a person to buy 10.5 kg more for Rs. 1,000. What is the reduced price of rice per kg?'),
  ('2024',93,E'The simple interest on a sum of Rs. 8,000 at a certain rate percent per annum for 3 years is Rs. 3,600. If the interest is compounded 8-monthly on the same sum at the same interest rate, then total compound interest after 2 years will be'),
  ('2024',94,E'The sides of a triangle are 5, 12 and 13 units. A rectangle is constructed, which is equal in area to the triangle. It has a width of 10 units, then the perimeter of this rectangle is:'),
  ('2024',96,E'The mean of 100 observations was calculated as 49. It was later discovered that three observations taken as 40, 20, 50 were actually 60, 70, 80 respectively. The correct mean is'),
  ('2024',97,E'Ten different letters of alphabets are given. Words with five letters are formed from these given letters. Then, the number of words which have at least one repeated letter is:'),
  ('2024',99,E'Recently which app is launched by Jaipur Municipal Corporation, Heritage for citizens to report civic issues and government to analyze, track, manage & solve?'),
  ('2024',101,E'Which one of the following statement is NOT correct regarding the Rajasthan Legislative Assembly by-election-2024?'),
  ('2024',102,E'Choose the correct statement with regards to Guru Ghasidas - Tamor Pingla Tiger Reserve.'),
  ('2024',103,E'Which of the following Institution has been engaged by the Competition Commission of India in 2024, to conduct a market study on Artificial Intelligence and Competition?'),
  ('2024',104,E'The ''Rajasthan MSME Policy 2024'' will remain in force until which of the following date?'),
  ('2024',105,E'Recently Yamandu Orsi has been elected as the President of which country?'),
  ('2024',106,E'The Submarine Cable Resilience Summit in February, 2025 will be held at:'),
  ('2024',107,E'Name the writer from South Korea who has won the Nobel Prize for Literature in 2024?'),
  ('2024',108,E'Match the Column I and II regarding National awards for the empowerment of persons with disabilities 2024:\nColumn-I (Sarvshreshth Divyangjan)\n(a) Ananya Bijesh\n(b) Prateek Khandelwal\n(c) Priyanka Deepak Dabade\nColumn-II (Field of outstanding work)\n(i) Art and Culture\n(ii) Music\n(iii) Accessibility\nCodes:'),
  ('2024',110,E'The I Edition of Joint Table Top Exercise (CINBAX) between the Indian Army and the Cambodian Army was held at:'),
  ('2024',111,E'Where was the India - Norway business round table held on 8th December, 2024?'),
  ('2024',112,E'Which organization has recently launched an upgraded Mobile App "Suvidha 2.0"?'),
  ('2024',113,E'Consider the following statements about recently inaugurated Asia''s largest and world''s highest imaging Cherenkov Observatory, at Hanle, Ladakh:\nI. It was inaugurated by Ajit Kumar Mohanty, Chairman, Atomic Energy Commission.\nII. It is located at an altitude of 5100 metres.\nIII. The telescope is built by Bhabha Atomic Research Centre with the support of Electronic Corporation of India and other industry partners.\nChoose the correct answer from the options given below :'),
  ('2024',114,E'Who among the following from India, co-chaired with Mr. Atsushi Mimura, at the 2nd India - Japan Finance Dialogue held at Tokyo in September, 2024?'),
  ('2024',115,E'Khelo India Youth Games 2025 will be hosted by which of the following state?'),
  ('2024',117,E'Consider the following statements regarding to 38th National Games 2025 and choose the correct option:\nStatement (A): It will be hosted by Uttarakhand.\nStatement (B): The National Games will feature 28 sporting disciplines and 4 demonstration events.'),
  ('2024',118,E'How many gold and bronze medals has Rajasthan won in 5th National Para Shooting Championship held at Pune in November 2024?'),
  ('2024',119,E'''Divith Reddy Adulla'' winner of World Cadet Under-8 Championship 2024 is related to which game?'),
  ('2024',120,E'Which of the following archaeological sites was identified by archaeologist T.H. Handley as a Buddhist town?'),
  ('2024',121,E'Consider the following statements about Rao Chunda of Marwar and choose the correct option from below:\nA. Rao Chunda obtained Mandore in dowry.\nB. Rao Ranmal ascended the throne immediately after Rao Chunda''s death.'),
  ('2024',122,E'According to "Rao-Jetsi-Ro-Chhanda", who among the following was defeated by Rao Jaitsi, the ruler of Bikaner?'),
  ('2024',123,E'Which of the following was/were associated in the excavation of Ojiyana?\nA. R.C. Agrawal\nB. B.R. Meena\nC. Alok Tripathi\nCodes:'),
  ('2024',124,E'Consider the following statements related to Bijolia Peasant Movement:\nA. Vijay Singh Pathik had gone to Wardha to meet Gandhiji to give information regarding the Bijolia Peasant Movement.\nB. Prayag''s Abhyudaya and Calcutta''s Bharat Mitra newspaper regularly published news related to the Bijolia Peasant Movement.\nSelect the correct answer using the codes given below :'),
  ('2024',125,E'The S.A. Sudhalkar report of 1945 is associated with which of the following Princely State?'),
  ('2024',126,E'Which of the following statements is not true regarding Walterkrit Rajput Hitkarini Sabha ?'),
  ('2024',127,E'The famous temple built by Mathandev at Rajorgarh was dedicated to which of the following deities?'),
  ('2024',128,E'Consider the following statements about the folk instrument ''Chautara'' and choose the correct option from below:\nA. It is a four stringed instrument.\nB. It is generally used in singing bhajans of Ramdev ji.'),
  ('2024',129,E'Which of the following options is not rightly matched?'),
  ('2024',130,E'Match List I with List II regarding famous painting styles and their painters of Rajasthan and select the correct option:\nList - I\nA. Kishangarh\nB. Bikaner\nC. Mewar\nD. Marwar\nList - II\ni. Sahibdeen\nii. Nihalchand\niii. Ali Raza\niv. Shivdas\nCodes:'),
  ('2024',131,E'Consider the following statements about Saint Laldas and choose the correct option from below:\nA. Saint Laldas remained unmarried throughout his life.\nB. After the death of Saint Laldas, a temple was built at his Samadhi place.'),
  ('2024',132,E'Which of the following colours is ''Kasumal'', which is used in the costumes of Rajasthan?'),
  ('2024',133,E'Consider the following statements about Matsya Union''s Prime Minister Shobaram and choose the correct option from below:\nA. He left his legal profession during the Non-Cooperation Movement.\nB. He was the member of the Cabinet of Heeralal Shastri.'),
  ('2024',134,E'For which of the following the words Aadi , Hiyali are popular in Rajasthani language?'),
  ('2024',135,E'Which of the following titles was adopted by the Kadphises Second of Kushan dynasty?'),
  ('2024',136,E'Consider the following statements about Stupas and choose the correct option from below:\nA. The word ''Stupa'' is an architectural term and means something which is raised up by accumulation.\nB. The custom of erecting ''Stupas'' as a form of memorial to the dead was pre-Buddhist.'),
  ('2024',137,E'Which of the following Buddhist texts were written in Sanskrit language? Choose the correct option from below:\nA. Divyavadan\nB. Deepvansha\nC. Mahavansha\nD. Aryamanjushree Moolkalp'),
  ('2024',138,E'Consider the following statements related to Aajivaka Sect :\nA. Belief in Determinism\nB. The order of reincarnation can be changed.\nC. Belief in Austerity\nSelect the correct answer using the codes given below:'),
  ('2024',139,E'Which of the following monuments were built by Emperor Shershah?\nA. Sasaram Tomb\nB. Kila-E-Kuhn Mosque\nC. Tomb of Sikandara\nD. Jama Masjid'),
  ('2024',140,E'Which of the following statements is not correct regarding the Bhakti Movement?'),
  ('2024',141,E'Who painted the famous image of Bharat Mata to visually associate the identity of India, as a Nation?'),
  ('2024',142,E'In which language did the poet Mallanarya write the texts named "Bhava Chinta Ratna" and "Veerasaivamrita" in the court of Krishandev Ray?'),
  ('2024',143,E'Who among the following was appointed as the chairman of Secondary Education Commission by Government of India in 1952?'),
  ('2024',144,E'Match List - I with List - II and select the correct answer by using the codes given below :\nList - I (Desert)\nA. Gobi\nB. Patagonia\nC. Victoria\nD. Kalahari\nList - II (Location)\ni. Southern Africa\nii. Asia\niii. South America\niv. Australia\nCodes:'),
  ('2024',145,E'Which is not an area of Mediterranean type of Agriculture?'),
  ('2024',146,E'Read the following statements related to the liberal phase of Indian National Movement (1885-1905 A.D.):\nA. Supported the rich democratic and scientific culture of modern Europe.\nB. Strongly criticized the Economic aspect of British imperialism.\nSelect the correct answer using the codes given below:'),
  ('2024',147,E'What is the correct order of the following mountain ranges from North to South?\nA. Ladakh\nB. Shiwalik\nC. Karakoram\nD. Zaskar\nCodes:'),
  ('2024',148,E'Which one of the following statements is not correct?'),
  ('2024',149,E'Match List I with List II and select the correct answer using the codes given below:\nList - I (Tributary)\nA. Rapti\nB. Tista\nC. Hiran\nD. Purna\nList - II (River)\ni. Brahmaputra\nii. Narmada\niii. Godavari\niv. Ghaghra\nCodes:'),
  ('2024',150,E'In which forest zone of the world highest deforestation has been recorded?')
) as v(yr, qno, stem)
where t.source_year = v.yr and t.paper_qno = v.qno and t.q is distinct from v.stem;
